version: "3.9"

services:
  migrate:
    build: .
    command: sh -c "npx prisma migrate deploy && node prisma/seed.js"
    volumes:
      - db_data:/data

  web:
    build: .
    container_name: nextjs-app
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - migrate
    environment:
      NODE_ENV: production

      # Prisma SQLite
      DATABASE_URL: file:/data/db.sqlite

      # NextAuth (nếu dùng)
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}

    volumes:
      - db_data:/data                 # SQLite DB
      - uploads:/app/public/uploads  # user uploads

volumes:
  db_data:
  uploads: