-- AlterTable
ALTER TABLE "Image" ADD COLUMN "title" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Image" ADD COLUMN "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Image" ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false;
